# Generated by Django 5.2.4 on 2025-07-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_courseratings_likes_alter_reviewcomment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='nom',
            new_name='name',
        ),
    ]
