# Generated by Django 5.2.4 on 2025-09-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_rename_nom_courses_name'),
        ('teachers', '0003_alter_teachers_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
