# Generated by Django 5.2.4 on 2025-09-10 18:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_rename_courses_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseRatings',
            new_name='CourseRating',
        ),
    ]
