# Generated by Django 5.2.4 on 2025-08-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_reviewcomment_reviewlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='picture',
            field=models.ImageField(null=True, upload_to='teacher_images/'),
        ),
    ]
