# Generated by Django 5.2.4 on 2025-09-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_rename_courses_course'),
        ('teachers', '0003_alter_teachers_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
