# Generated by Django 5.2.4 on 2025-09-10 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_rename_teachers_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherRatings',
            new_name='TeacherRating',
        ),
    ]
