# Generated by Django 5.2.4 on 2025-10-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_rename_teacherratings_teacherrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrating',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
